version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/aws-labs/env"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  - package-ecosystem: "pip"
    directory: "/azure-labs/env"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"